site_name: Safe Travels Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - roamlinks

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - toc:
      permalink: true