# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Safe Travels Documentation
site_url: https://l4valamp.github.io/safetravels-docs/

theme:
  name: material
  palette: 
    scheme: slate
    primary: deep orange
    accent: orange
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages #this is a plugin it doesnt recognize but works fine
  - roamlinks #this too

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - toc:
      permalink: true