# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Safe Travels Documentation
site_url: https://l4valamp.github.io/safetravels-docs/

theme:
  name: material
  palette: 
    scheme: slate
    primary: amber
    accent: yellow
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - content.code.copy

plugins:
  - search
  - awesome-pages #this is a plugin it doesnt recognize but works fine
  - roamlinks #this too
  - entity #this is our custom plugin for variables

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
     alternate_style: true
  - pymdownx.snippets
  - tables
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/entities.js
